env:
  es2021: true
  webextensions: true
extends:
  - 'standard'
overrides:
  - files:
      - '*.html'
    parser: '@html-eslint/parser'
    extends:
      - 'plugin:@html-eslint/recommended'
parserOptions:
  ecmaVersion: latest
rules: {}
plugins:
  - '@html-eslint'
